"""
RepurposeAlpha — PDF report generator.

Uses reportlab (pure Python, no external binaries) + matplotlib for charts.
Produces a 6-page report suitable for pipeline review or grant submission.
"""
import io
from datetime import datetime
from pathlib import Path

import pandas as pd
import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import seaborn as sns

from reportlab.lib import colors
from reportlab.lib.pagesizes import LETTER
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Image, Table, TableStyle,
    PageBreak,
)


def _render_heatmap(corr: pd.DataFrame) -> io.BytesIO:
    fig, ax = plt.subplots(figsize=(6, 4.5))
    sns.heatmap(corr, annot=True, fmt=".2f", cmap="RdYlGn_r",
                vmin=0, vmax=1, square=True, ax=ax,
                cbar_kws={"label": "Correlation"})
    ax.set_title("Candidate correlation matrix")
    plt.tight_layout()
    buf = io.BytesIO()
    plt.savefig(buf, format="png", dpi=120, bbox_inches="tight")
    plt.close(fig)
    buf.seek(0)
    return buf


def _render_frontier(mu: pd.Series, sigma: pd.Series, cov: pd.DataFrame) -> io.BytesIO:
    n = 2000
    rng = np.random.default_rng(42)
    rand_w = rng.dirichlet(np.ones(len(mu)), n)
    rets = rand_w @ mu.values
    vols = np.sqrt(np.einsum("ij,jk,ik->i", rand_w, cov.values, rand_w))

    fig, ax = plt.subplots(figsize=(6, 4.5))
    sc = ax.scatter(vols, rets, c=rets / np.maximum(vols, 1e-6),
                    s=6, cmap="viridis", alpha=0.6)
    ax.set_xlabel("Risk (volatility)")
    ax.set_ylabel("Expected return")
    ax.set_title("Efficient frontier (Monte Carlo approximation)")
    ax.grid(alpha=0.3)
    plt.tight_layout()
    buf = io.BytesIO()
    plt.savefig(buf, format="png", dpi=120, bbox_inches="tight")
    plt.close(fig)
    buf.seek(0)
    return buf


def _render_weights(w_sharpe: pd.Series, w_minvol: pd.Series) -> io.BytesIO:
    fig, ax = plt.subplots(figsize=(6, 4.0))
    df = pd.DataFrame({"Max Sharpe": w_sharpe, "Min Vol": w_minvol})
    df.plot(kind="bar", ax=ax, color=["#3b82f6", "#94a3b8"])
    ax.set_ylabel("Portfolio weight")
    ax.set_title("Optimal portfolio weights")
    ax.grid(alpha=0.3, axis="y")
    plt.xticks(rotation=30, ha="right")
    plt.tight_layout()
    buf = io.BytesIO()
    plt.savefig(buf, format="png", dpi=120, bbox_inches="tight")
    plt.close(fig)
    buf.seek(0)
    return buf


def _flatten_registry(reg: dict) -> list:
    rows = []
    def walk(node, prefix=""):
        for k, v in node.items():
            path = f"{prefix}.{k}" if prefix else k
            if isinstance(v, dict) and "value" in v:
                rows.append({
                    "key": path,
                    "value": v["value"],
                    "confidence": v.get("confidence", "?"),
                    "source": str(v.get("source", ""))[:80],
                })
            elif isinstance(v, dict):
                walk(v, path)
    walk(reg)
    return rows


def build_report(path: Path, title: str, user: str, disease: str,
                 corr: pd.DataFrame, mu: pd.Series, sigma: pd.Series,
                 cov: pd.DataFrame, w_sharpe: pd.Series, w_minvol: pd.Series,
                 registry: dict, findings: str = "") -> Path:
    """Generate a 6-page PDF report. Returns the output path."""
    styles = getSampleStyleSheet()
    h1 = ParagraphStyle("h1", parent=styles["Heading1"], fontSize=24, leading=28,
                        textColor=colors.HexColor("#1e40af"))
    h2 = ParagraphStyle("h2", parent=styles["Heading2"], fontSize=14,
                        textColor=colors.HexColor("#334155"), spaceAfter=8)
    body = ParagraphStyle("body", parent=styles["BodyText"], fontSize=10, leading=14)

    story = []

    # ---------------- Page 1: Title ----------------
    story.append(Spacer(1, 1.2 * inch))
    story.append(Paragraph(title, h1))
    story.append(Spacer(1, 0.3 * inch))
    story.append(Paragraph(f"<b>Disease focus:</b> {disease}", body))
    story.append(Paragraph(f"<b>Generated by:</b> {user}", body))
    story.append(Paragraph(f"<b>Date:</b> {datetime.now().strftime('%Y-%m-%d %H:%M')}", body))
    story.append(Spacer(1, 0.5 * inch))
    story.append(Paragraph(
        "This report was generated programmatically by RepurposeAlpha. "
        "Every numeric input is sourced from the assumption registry; "
        "see the final page for full provenance.",
        body))
    story.append(PageBreak())

    # ---------------- Page 2: Methodology & Findings ----------------
    story.append(Paragraph("Methodology", h2))
    story.append(Paragraph(
        "RepurposeAlpha applies Modern Portfolio Theory to drug repurposing. "
        "Candidate drugs are treated as correlated, risky assets. Correlations are "
        "computed from public bioactivity data (ChEMBL), chemical structure similarity, "
        "mechanism of action, and WHO ATC classification. Portfolio weights are selected "
        "by maximizing the Sharpe ratio subject to long-only constraints.",
        body))
    story.append(Spacer(1, 0.3 * inch))
    story.append(Paragraph("Key findings", h2))
    if findings:
        story.append(Paragraph(findings, body))
    else:
        story.append(Paragraph(
            "See the correlation matrix on the next page for candidate relationships.",
            body))
    story.append(PageBreak())

    # ---------------- Page 3: Correlation matrix ----------------
    story.append(Paragraph("Correlation matrix", h2))
    story.append(Paragraph(
        "1.0 = identical bet. 0.0 = fully independent. Values above 0.5 indicate "
        "the two candidates share a biological hypothesis and should be treated as "
        "a concentrated position.", body))
    story.append(Spacer(1, 0.2 * inch))
    story.append(Image(_render_heatmap(corr), width=6.0 * inch, height=4.5 * inch))
    story.append(PageBreak())

    # ---------------- Page 4: Efficient frontier + weights ----------------
    story.append(Paragraph("Efficient frontier & portfolio weights", h2))
    story.append(Image(_render_frontier(mu, sigma, cov), width=6.0 * inch, height=4.5 * inch))
    story.append(Spacer(1, 0.2 * inch))
    story.append(Image(_render_weights(w_sharpe, w_minvol), width=6.0 * inch, height=4.0 * inch))
    story.append(PageBreak())

    # ---------------- Page 5: Weight table ----------------
    story.append(Paragraph("Recommended allocations", h2))
    rows = [["Candidate", "Max Sharpe", "Min Volatility"]]
    for t in w_sharpe.index:
        rows.append([t, f"{w_sharpe[t]:.3f}", f"{w_minvol[t]:.3f}"])
    tbl = Table(rows, colWidths=[3.0 * inch, 1.5 * inch, 1.5 * inch])
    tbl.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1e40af")),
        ("TEXTCOLOR",  (0, 0), (-1, 0), colors.white),
        ("FONTNAME",   (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE",   (0, 0), (-1, -1), 10),
        ("ALIGN",      (1, 1), (-1, -1), "CENTER"),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f1f5f9")]),
        ("GRID", (0, 0), (-1, -1), 0.3, colors.HexColor("#cbd5e1")),
    ]))
    story.append(tbl)
    story.append(PageBreak())

    # ---------------- Page 6: Assumption registry ----------------
    story.append(Paragraph("Assumption registry", h2))
    story.append(Paragraph(
        "Every numeric input is listed below with its source and confidence label.",
        body))
    story.append(Spacer(1, 0.2 * inch))

    reg_rows = [["Key", "Value", "Conf.", "Source"]]
    for r in _flatten_registry(registry):
        reg_rows.append([
            r["key"][:42], str(r["value"])[:18],
            r["confidence"], r["source"][:55],
        ])
    tbl = Table(reg_rows, colWidths=[1.9 * inch, 1.0 * inch, 0.6 * inch, 2.6 * inch], repeatRows=1)
    tbl.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1e40af")),
        ("TEXTCOLOR",  (0, 0), (-1, 0), colors.white),
        ("FONTNAME",   (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE",   (0, 0), (-1, -1), 7.5),
        ("VALIGN",     (0, 0), (-1, -1), "TOP"),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f1f5f9")]),
        ("GRID", (0, 0), (-1, -1), 0.2, colors.HexColor("#cbd5e1")),
    ]))
    story.append(tbl)

    # ---- Write PDF ----
    doc = SimpleDocTemplate(str(path), pagesize=LETTER,
                            title=title, author=user)
    doc.build(story)
    return path
